name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Flutter Pub Get
        run: |
          cd lushmkt_mobile
          flutter pub get

      - name: Enable iOS
        run: |
          cd lushmkt_mobile
          flutter config --enable-ios

      - name: Install CocoaPods
        run: |
          cd lushmkt_mobile/ios
          pod install

      - name: Build iOS No Codesign
        run: |
          cd lushmkt_mobile
          flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd lushmkt_mobile
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r LushMKT.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: LushMKT-IPA
          path: lushmkt_mobile/LushMKT.ipa